/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Metodo.Logica;
import java.util.StringTokenizer;
import java.lang.String;
import java.util.Locale;
import javax.swing.JOptionPane;


/**
 *
 * @author BRAYHAN
 */
public class Interfaz extends javax.swing.JFrame {
   
    Logica miLogica;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        miLogica = new Logica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPalabra2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txtIgual = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVocales = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtConsonantes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEnmascarar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("PALABRAS");
        jLabel1.setBounds(20, 220, 70, 14);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtPalabra.setBounds(200, 210, 100, 30);
        jLayeredPane1.add(txtPalabra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("PALABRA DE COMPARACION");
        jLabel4.setBounds(20, 250, 200, 20);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtPalabra2.setBounds(200, 250, 100, 30);
        jLayeredPane1.add(txtPalabra2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(70, 480, 130, 40);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setText("PRIMERA PALABRA");
        jLabel2.setBounds(20, 30, 140, 20);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("SEGUNDA PALABRA");
        jLabel3.setBounds(20, 70, 160, 20);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("SI SON IGUALES");
        jLabel5.setBounds(20, 110, 120, 14);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("NUMERO DE CARACTERES");
        jLabel6.setBounds(20, 150, 160, 14);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txt1.setBounds(190, 20, 140, 30);
        jLayeredPane2.add(txt1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txt2.setBounds(190, 60, 140, 30);
        jLayeredPane2.add(txt2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtIgual.setBounds(190, 100, 140, 30);
        jLayeredPane2.add(txtIgual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtNum.setBounds(190, 140, 140, 30);
        jLayeredPane2.add(txtNum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("VOCALES");
        jLabel7.setBounds(20, 190, 70, 20);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtVocales.setBounds(190, 180, 140, 30);
        jLayeredPane2.add(txtVocales, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("CONSONANTES");
        jLabel8.setBounds(20, 220, 110, 20);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtConsonantes.setBounds(190, 220, 140, 30);
        jLayeredPane2.add(txtConsonantes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText("CORREO ELECTRONICO");
        jLabel10.setBounds(20, 260, 160, 20);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtCorreo.setBounds(190, 260, 140, 30);
        jLayeredPane2.add(txtCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText("LETRAS");
        jLabel11.setBounds(30, 310, 80, 14);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtLetra.setBounds(190, 300, 140, 30);
        jLayeredPane2.add(txtLetra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setText("ENMASCARAR");
        jLabel12.setBounds(30, 350, 130, 14);
        jLayeredPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtEnmascarar.setBounds(190, 340, 140, 30);
        jLayeredPane2.add(txtEnmascarar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(320, 20, 360, 430);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("TELEFONO");
        jLabel9.setBounds(20, 290, 80, 20);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtTelefono.setBounds(200, 290, 100, 30);
        jLayeredPane1.add(txtTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("OPERADOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(230, 480, 140, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int contadorVocales = 0;
        int contadorConsonantes = 0;

        String vocal = txtVocales.getText();
        String palabra = txtPalabra.getText();
        String cadena = txtPalabra2.getText();

        StringTokenizer tokens = new StringTokenizer(palabra, ", ");

        while (tokens.hasMoreTokens()) {

            txt1.setText(String.valueOf(tokens.nextToken()).toUpperCase());
            txt2.setText(String.valueOf(tokens.nextToken()).toUpperCase());
        }

        for (int i = 0; i < palabra.length(); i++) {
            if (palabra.charAt(i) == 'a' || palabra.charAt(i) == 'e' || palabra.charAt(i) == 'i' || palabra.charAt(i) == 'o' || palabra.charAt(i) == 'u') {
                contadorVocales++;
            }
        }

        for (int j = 0; j < palabra.length(); j++) {
            if (palabra.charAt(j) == 'b' || palabra.charAt(j) == 'c' || palabra.charAt(j) == 'd' || palabra.charAt(j) == 'f' || palabra.charAt(j) == 'g' || palabra.charAt(j) == 'h'
                    || palabra.charAt(j) == 'j' || palabra.charAt(j) == 'k' || palabra.charAt(j) == 'l' || palabra.charAt(j) == 'm' || palabra.charAt(j) == 'n' || palabra.charAt(j) == 'p'
                    || palabra.charAt(j) == 'q' || palabra.charAt(j) == 'r' || palabra.charAt(j) == 's' || palabra.charAt(j) == 't' || palabra.charAt(j) == 'v' || palabra.charAt(j) == 'w'
                    || palabra.charAt(j) == 'x' || palabra.charAt(j) == 'y' || palabra.charAt(j) == 'z') {
                contadorConsonantes++;
            }
        }

       if(palabra.contains("a")||palabra.contains("e")||palabra.contains("i")){
           
         txtEnmascarar.setText(String.valueOf(palabra+"*"));
       }
       
       
       else{
           txtEnmascarar.setText(String.valueOf(palabra));
       }
        if (txtPalabra.getText().contains("@") || txtPalabra.getText().contains(".")) {

            txtCorreo.setText(String.valueOf("ES UN CORREO "));
        } else {
            txtCorreo.setText(String.valueOf("NO ES UN CORREO "));
        }

        if (txtLetra.getText().contains("e")) {

            txtLetra.setText(String.valueOf("LETRA e"));
        }

        if (txtLetra.getText().contains("E")) {

            txtLetra.setText(String.valueOf("LETRA E"));
        } else {
            txtLetra.setText(String.valueOf("NINGUNA"));
        }

        txtIgual.setText(String.valueOf(palabra.equals(cadena)));
        txtNum.setText(String.valueOf(palabra.length() + cadena.length()));
        txtVocales.setText(String.valueOf(contadorVocales));
        txtConsonantes.setText(String.valueOf(contadorConsonantes++));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (txtTelefono.getText().contains("310") || txtTelefono.getText().contains("311") || txtTelefono.getText().contains("312") || txtTelefono.getText().contains("313") || txtTelefono.getText().contains("314") || txtTelefono.getText().contains("320")) {
            JOptionPane.showMessageDialog(this, "SU OPERADOR ES CLARO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        }

        if (txtTelefono.getText().contains("315") || txtTelefono.getText().contains("316") || txtTelefono.getText().contains("317") || txtTelefono.getText().contains("318")) {
            JOptionPane.showMessageDialog(this, "SU OPERADOR ES MOVISTAR", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        }

        if (txtTelefono.getText().contains("300") || txtTelefono.getText().contains("301")) {
            JOptionPane.showMessageDialog(this, "SU OPERADOR ES TIGO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed

        
        
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtConsonantes;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEnmascarar;
    private javax.swing.JTextField txtIgual;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtPalabra;
    private javax.swing.JTextField txtPalabra2;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVocales;
    // End of variables declaration//GEN-END:variables
}


